- name: install ngnix
  hosts: ngnix
  become: true
  tasks:

    - name: disable nginx 
      ansible.builtin.command: dnf module disable nginx -y

    - name: enable  nginx 
      ansible.builtin.command: dnf module enable nginx:1.24 -y

    - name: install ngnix
      ansible.builtin.dnf: 
       name: nginx
       state: present 

    - name: Recursively remove a directory
      ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent


    - name: create html directory
      ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory


    - name:  dowmload catalouge code
      ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

    - name: unzip direciory
      ansible.builten.unarchive:
      src:  /tmp/frontend.zip
      dest: /usr/share/nginx/html  
      remote_src: yes
      
    - name: remove default nginx conf
      ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

    - name: copy service file
      ansible.builtin.copy:
      src: ngnix.service
      dest: /etc/nginx/nginx.conf

    - name: restart nginx
      ansible.builtin.service:
        name: ngnix
        state: restarted